obs: # input into policy
  sideview_image:
    modality: "ImageModality"
    dim: [112, 112, 3]
    camera: "primary"
  robot0_eye_in_hand_image:
    modality: "ImageModality"
    dim: [112, 112, 3]
    camera: "wrist"
  robot0_eef_pos:
    modality: "FloatVectorModality"
    dim: 3
  robot0_eef_quat:
    modality: "FloatVectorModality"
    dim: 4
  robot0_gripper_qpos:
    modality: "FloatVectorModality"
    dim: 2
  # robot0_joint_pos:
  #   modality: "FloatVectorModality"
  #   dim: 7
  # object:
  #   modality: "FloatVectorModality"
  #   dim: 44
actions:
  type: "action_trajectory"
  modality: "FloatVectorModality"
  dim: 7 # x0,y0,z0,x1,y1,z1,grasp0,grasp1
task:
  language_instruction: "Pick up and hang tool"
