obs: # input into policy
  robot0_eef_pos:
    modality: "FloatVectorModality"
    normalize: True
    obs_encoder:
      input_dim: 3
      output_dim: 3
      layer_dims: null
      activation: "ReLU" # [ReLU, Tanh...]
  robot0_eef_quat:
    modality: "FloatVectorModality"
    normalize: True
    obs_encoder:
      input_dim: 4
      output_dim: 4
      layer_dims: null
      activation: "ReLU" # [ReLU, Tanh...]
  robot0_gripper_qpos:
    modality: "FloatVectorModality"
    normalize: True
    obs_encoder:
      input_dim: 2
      output_dim: 2
      layer_dims: null
      activation: "ReLU" # [ReLU, Tanh...]
  agentview_image:
    modality: "ImageModality"
    normalize: False
    data_augmentation: False
    obs_encoder:
      model: "VariationalAutoEncoder"
      model_path: null
      model_kwargs:
        input_size: [128, 128]
        input_channel: 3
        channels: [8, 16, 32, 64, 128, 256]
        encoder_kernel_sizes: [3, 3, 3, 3, 3, 3]
        decoder_kernel_sizes: [3, 4, 4, 4, 4, 4]
        strides: [2, 2, 2, 2, 2, 2]
        paddings: [1, 1, 1, 1, 1, 1]
        latent_dim: 16
        kld_weight: 1e-2
        # activation: "ReLU" # TODO
        # normalization: "BatchNorm2d"
        # output_activation: "Sigmoid"
      trainable: True
      input_dim: [128, 128, 3]
      activation: "ReLU"
      layer_dims: null
      output_dim: 32
      has_decoder: True
      freeze: True
  robot0_eye_in_hand_image:
    modality: "ImageModality"
    normalize: False
    data_augmentation: False
    obs_encoder:
      model: "VariationalAutoEncoder"
      model_path: null
      model_kwargs:
        input_size: [128, 128]
        input_channel: 3
        channels: [8, 16, 32, 64, 128, 256]
        encoder_kernel_sizes: [3, 3, 3, 3, 3, 3]
        decoder_kernel_sizes: [3, 4, 4, 4, 4, 4]
        strides: [2, 2, 2, 2, 2, 2]
        paddings: [1, 1, 1, 1, 1, 1]
        latent_dim: 32
        # activation: "ReLU" # TODO
        # normalization: "BatchNorm2d"
        # output_activation: "Sigmoid"
      trainable: True
      input_dim: [128, 128, 3]
      activation: "ReLU"
      layer_dims: null
      output_dim: 32
      has_decoder: True
      freeze: True
actions:
  modality: "FloatVectorModality"
  dim: 7
  normalize: True

network:
  policy:
    model: "RNNActor"
    model_path: null
    rnn:
      type: "LSTM"
      rnn_horizon: 20
      rnn_num_layers: 2
      rnn_hidden_dim: 1000
      open_loop: False # TODO
      kwargs:
        bidirectional: False
    mlp_decoder:
      layer_dims: []
      activation: "ReLU"
      squash_output: True
    gmm:
      enabled: False
      modes: 5
      min_std: 0.0001
      low_noise_eval: True
      use_tanh: False
      std_activation: "F.softplus" # or torch.exp
    train:
      num_epochs: 1000
      batch_size: 4096
      criterion: "MSELoss"
      lr: 1e-4
      lr_scheduler: True
      supervise_all_steps: True
      optimizer: "AdamW"
      weight_decay: 0.01
      max_grad_norm: null # null or 1, 3, 5,...
      weight:
        l1: 0.0
        l2: 1.0

dataset:
  dataset_keys: ["actions"]
  load_next_obs: False
  frame_stack: 1
  seq_length: 20
  pad_frame_stack: True
  pad_seq_length: True
  get_pad_mask: False
  goal_mode: null
  hdf5_cache_mode: "all"
  hdf5_use_swmr: True
