# @package _global_

fps: 20

env:
  name: robomimic
  task: Lift
  image_size: 112
  state_dim: 9
  action_dim: 7
  fps: ${fps}
  episode_length: 100
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
