from gymnasium.envs.registration import register

ROBOMIMIC_ENV_METADATA = {
    "Lift": {
        "env_name": "Lift",
        "env_version": "1.4.1",
        "type": 1,
        "env_kwargs": {
            "has_renderer": False,
            "has_offscreen_renderer": True,
            "ignore_done": True,
            "use_object_obs": True,
            "use_camera_obs": True,
            "control_freq": 20,
            "controller_configs": {
                "type": "OSC_POSE",
                "input_max": 1,
                "input_min": -1,
                "output_max": [0.05, 0.05, 0.05, 0.5, 0.5, 0.5],
                "output_min": [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5],
                "kp": 150,
                "damping": 1,
                "impedance_mode": "fixed",
                "kp_limits": [0, 300],
                "damping_limits": [0, 10],
                "position_limits": None,
                "orientation_limits": None,
                "uncouple_pos_ori": True,
                "control_delta": True,
                "interpolation": None,
                "ramp_ratio": 0.2,
            },
            "robots": ["Panda"],
            "camera_depths": False,
            "camera_heights": 224,
            "camera_widths": 224,
            "reward_shaping": False,
            "camera_names": ["agentview", "robot0_eye_in_hand"],
            "render_gpu_device_id": 0,
        },
    },
    "Can": {
        "env_name": "PickPlaceCan",
        "env_version": "1.4.1",
        "type": 1,
        "env_kwargs": {
            "has_renderer": False,
            "has_offscreen_renderer": True,
            "ignore_done": True,
            "use_object_obs": True,
            "use_camera_obs": True,
            "control_freq": 20,
            "controller_configs": {
                "type": "OSC_POSE",
                "input_max": 1,
                "input_min": -1,
                "output_max": [0.05, 0.05, 0.05, 0.5, 0.5, 0.5],
                "output_min": [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5],
                "kp": 150,
                "damping": 1,
                "impedance_mode": "fixed",
                "kp_limits": [0, 300],
                "damping_limits": [0, 10],
                "position_limits": None,
                "orientation_limits": None,
                "uncouple_pos_ori": True,
                "control_delta": True,
                "interpolation": None,
                "ramp_ratio": 0.2,
            },
            "robots": ["Panda"],
            "camera_depths": False,
            "camera_heights": 224,
            "camera_widths": 224,
            "reward_shaping": False,
            "camera_names": ["agentview", "robot0_eye_in_hand"],
            "render_gpu_device_id": 0,
        },
    },
    "Square": {
        "env_name": "NutAssemblySquare",
        "env_version": "1.4.1",
        "type": 1,
        "env_kwargs": {
            "has_renderer": False,
            "has_offscreen_renderer": True,
            "ignore_done": True,
            "use_object_obs": True,
            "use_camera_obs": True,
            "control_freq": 20,
            "controller_configs": {
                "type": "OSC_POSE",
                "input_max": 1,
                "input_min": -1,
                "output_max": [0.05, 0.05, 0.05, 0.5, 0.5, 0.5],
                "output_min": [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5],
                "kp": 150,
                "damping": 1,
                "impedance_mode": "fixed",
                "kp_limits": [0, 300],
                "damping_limits": [0, 10],
                "position_limits": None,
                "orientation_limits": None,
                "uncouple_pos_ori": True,
                "control_delta": True,
                "interpolation": None,
                "ramp_ratio": 0.2,
            },
            "robots": ["Panda"],
            "camera_depths": False,
            "camera_heights": 224,
            "camera_widths": 224,
            "reward_shaping": False,
            "camera_names": ["agentview", "robot0_eye_in_hand"],
            "render_gpu_device_id": 0,
        },
    },
    "ToolHang": {
        "env_name": "ToolHang",
        "env_version": "1.4.1",
        "type": 1,
        "env_kwargs": {
            "has_renderer": False,
            "has_offscreen_renderer": True,
            "ignore_done": True,
            "use_object_obs": True,
            "use_camera_obs": True,
            "control_freq": 20,
            "controller_configs": {
                "type": "OSC_POSE",
                "input_max": 1,
                "input_min": -1,
                "output_max": [0.05, 0.05, 0.05, 0.5, 0.5, 0.5],
                "output_min": [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5],
                "kp": 150,
                "damping": 1,
                "impedance_mode": "fixed",
                "kp_limits": [0, 300],
                "damping_limits": [0, 10],
                "position_limits": None,
                "orientation_limits": None,
                "uncouple_pos_ori": True,
                "control_delta": True,
                "interpolation": None,
                "ramp_ratio": 0.2,
            },
            "robots": ["Panda"],
            "camera_depths": False,
            "camera_heights": 224,
            "camera_widths": 224,
            "reward_shaping": False,
            "camera_names": ["sideview", "robot0_eye_in_hand"],
            "render_gpu_device_id": 0,
        },
    },
}

register(
    id="RoboMimic-v0",
    entry_point="imitator.utils.env.gym_wrapper:RoboMimicEnv",
    max_episode_steps=1000,
)
